version: '3.3'

services:
  mysql:
    container_name: sbdh_mysql
    image: mysql:5.7
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: sbdh_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - $PMA_CLIENT_PORT:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql